#' @name constants
#' @title Constants for Use in the redcapAPI Package
#'
#' @description Constants that are used inside the package
#'

# The field names listed here are those generated by REDCap. 
# A listing of these fields was needed to support missingSummary.
# It wouldn't hurt to contemplate how these could be obtained 
# dynamically rather than relying up updating constants.

#' @export

REDCAP_SYSTEM_FIELDS <- c("redcap_event_name", 
                          "redcap_data_access_group", 
                          "redcap_repeat_instrument", 
                          "redcap_repeat_instance")


# UNEXPORTED --------------------------------------------------------

# These are variables in the Users table coded as 0 = No Access, 1 = Access
REDCAP_USER_TABLE_ACCESS_VARIABLES <- 
  c("design", 
    "user_rights", 
    "data_access_groups", 
    "reports", 
    "stats_and_charts", 
    "manage_survey_participants", 
    "calendar", 
    "data_import_tool", 
    "data_comparison_tool", 
    "logging", 
    "file_repository", 
    "data_quality_create", 
    "data_quality_execute", 
    "api_export", 
    "api_import", 
    "mobile_app", 
    "mobile_app_download_data", 
    "record_create", 
    "record_rename", 
    "record_delete", 
    "lock_records_all_forms", 
    "lock_records", 
    "lock_records_customization", 
    "mycap_participants", 
    "random_setup", 
    "random_dashboard", 
    "random_perform")

# This is used for File Repository methods. Some calls result in a
# result of an empty string or an error. At times we prefer to return
# the empty frame to maintain consistency in outputs with recursive calls
FILE_REPOSITORY_EMPTY_FRAME <- 
  data.frame(folder_id = numeric(0), 
             doc_id = numeric(0), 
             name = character(0), 
             parent_folder = numeric(0),
             stringsAsFactors = FALSE)

# This is used for cases when an import/export/delete to the file repository
# results in no changes and an empty frame is needed for the return

FILE_IMPORT_EXPORT_EMPTY_FRAME <- 
  data.frame(directory = character(0), 
             filename = character(0), 
             stringsAsFactors = FALSE)

# This is the list of fields recognized for updates in importProjectInformation

PROJECT_INFO_FIELDS_EDITABLE <- 
  c("project_title", 
    "project_language", 
    "purpose", 
    "purpose_other", 
    "project_notes", 
    "custom_record_label",
    "secondary_unique_field", 
    "is_longitudinal", 
    "surveys_enabled", 
    "scheduling_enabled", 
    "record_autonumbering_enabled", 
    "randomization_enabled", 
    "project_irb_number", 
    "project_grant_number", 
    "project_pi_firstname", 
    "project_pi_lastname", 
    "display_today_now_button", 
    "bypass_branching_erase_field_prompt")

PROJECT_INFO_FIELDS_FIXED <- 
  c("project_id",
    "creation_time",
    "production_time",
    "in_production",
    "has_repeating_instruments_or_events",
    "ddp_enabled",
    "missing_data_codes",
    "external_modules")