#' @name redcapDataStructures
#' @title REDCap Data Structures
#'
#' @description Utilities for recognizing and validating data structures 
#'   for use with the REDCap API
#' 
#' @param data `data.frame` User provided data to be compared against
#'   the established REDCap data structure.
#' @param redcap_data `data.frame` A data set from the `redcapAPI`
#'   package to use a reference for comparing to expected data structure. 

validateRedcapData <- function(data, redcap_data){
  if (is.null(data)) return(NULL)
  
  checkmate::assert_data_frame(x = data, 
                               col.names = "named")
  
  in_data_and_not_structure <- setdiff(names(data), 
                                       names(redcap_data))
  
  # names in data not in the redcap structure
  if (length(in_data_and_not_structure) > 0){
    warning("The following names in 'data' are not recognized in the REDCap data structure.\n", 
            "Downstream functions may not operate as expected. {", 
            paste0(in_data_and_not_structure, collapse = ", "), "}\n")
  }
  
  # names in the redcap structure not in the data
  
  in_structure_and_not_data <- setdiff(names(redcap_data), 
                                       names(data))
  
  if (length(in_structure_and_not_data) > 0){
    warning("The following names in the REDCap data structure are not in 'data'. \n", 
            "Downstream functions may not operate as expected. {", 
            paste0(in_structure_and_not_data, collapse = ", "), "}\n")
  }
  return(data)
}

#' @keywords internal
#' @importFrom utils read.csv
.getDataForm <- function() {
  fn <- system.file("extdata", "data_form.csv", package = "redcapAPI")
  x <- read.csv(fn,
    colClasses = c(
      field = 'character',
	  type = 'character',
	  v_start = 'character',
	  v_stop = 'character'
    )
  )
  rm_na_cols <- setdiff(names(x), c('v_start','v_stop'))
  for(i in rm_na_cols) x[is.na(x[,i]),i] <- 0
  x[x[,'v_start'] == '', 'v_start'] <- NA
  x[x[,'v_stop'] == '', 'v_stop'] <- NA
  x
}

data_form <- .getDataForm()

#' @keywords internal
.getStructure <- function(area, version) {
  coi <- c('field','type','v_start','v_stop')
  if(!(area %in% names(data_form))) stop('unknown structure type provided')
  df <- data_form[data_form[,area] == 1, coi]
  mk_type <- function(t) {
    switch(t,
      N = numeric(0),
	  T = as.POSIXct(character(0)),
	  character(0)
    )
  }
  r <- do.call(data.frame, c(mapply(mk_type, df[,'type']), stringsAsFactors = FALSE))
  names(r) <- df[,'field']
  torm <- logical(nrow(df))
  ix <- which(!is.na(df[,'v_start']))
  if(length(ix)) {
    cv <- vapply(df[ix,'v_start'], utils::compareVersion, numeric(1), a = version)
    torm[ix[cv < 0]] <- TRUE
  }
  ix <- which(!is.na(df[,'v_stop']))
  if(length(ix)) {
    cv <- vapply(df[ix,'v_stop'], utils::compareVersion, numeric(1), a = version)
    torm[ix[cv > 0]] <- TRUE
  }
  if(grepl('^f_', area)) {
    return(names(r)[!torm])
  }
  r[,!torm]
}

#' @rdname redcapDataStructures
#' @export

# The field names listed here are those generated by REDCap records export. 
# A listing of these fields was needed to support missingSummary.
# It would not hurt to contemplate how these could be obtained 
# dynamically rather than relying up updating constants.

REDCAP_SYSTEM_FIELDS <- .getStructure('f_SYSTEM', '14.4.0')

#' @rdname redcapDataStructures
#' @export

# These are the purposes that can be used when using 
# createRedcapProject

REDCAP_PROJECT_PURPOSE <- c("Practice/just for fun", 
                            "Other", 
                            "Research", 
                            "Quality Improvement", 
                            "Operational Support")

# Arms --------------------------------------------------------------
# Arms - Data Frame Structure

REDCAP_ARMS_STRUCTURE <- .getStructure('ARMS', '14.4.0')

# Data Access Groups ------------------------------------------------
# DAG Structure

REDCAP_DAG_STRUCTURE <- .getStructure('DAG', '14.4.0')

# DAG Assignment Structure

REDCAP_DAG_ASSIGNMENT_STRUCTURE <- .getStructure('DAG_ASSN', '14.4.0')

# Events ------------------------------------------------------------
# Event Structure

REDCAP_EVENT_STRUCTURE <- .getStructure('EVENT', '14.4.0')

# Field Names -------------------------------------------------------
# Field Name Structure 

REDCAP_FIELDNAME_STRUCTURE <- .getStructure('FIELDNAME', '14.4.0')

# Instruments -------------------------------------------------------
# Instrument Structure

REDCAP_INSTRUMENT_STRUCTURE <- .getStructure('INSTRUMENT', '14.4.0')

# Instrument Mapping Structure 

REDCAP_INSTRUMENT_MAPPING_STRUCTURE <- .getStructure('INSTRUMENT_MAP', '14.4.0')

# Logging -----------------------------------------------------------
# Logging Structure

REDCAP_LOGGING_STRUCTURE <- .getStructure('LOGGING', '14.4.0')

# Meta Data ---------------------------------------------------------
# Meta Data - Data Frame Structure 

REDCAP_METADATA_STRUCTURE <- .getStructure('METADATA', '14.4.0')

REDCAP_METADATA_API_UI_MAPPING <- 
  c("Variable...Field.Name" = "field_name", 
    "Form.Name" = "form_name", 
    "Section.Header" = "section_header", 
    "Field.Type" = "field_type", 
    "Field.Label" = "field_label", 
    "Choices..Calculations..OR.Slider.Labels" = "select_choices_or_calculations", 
    "Field.Note" = "field_note", 
    "Text.Validation.Type.OR.Show.Slider.Number" = "text_validation_type_or_show_slider_number", 
    "Text.Validation.Min" = "text_validation_min", 
    "Text.Validation.Max" = "text_validation_max", 
    "Identifier." = "identifier", 
    "Branching.Logic..Show.field.only.if...." = "branching_logic", 
    "Required.Field." = "required_field", 
    "Custom.Alignment" = "custom_alignment", 
    "Question.Number..surveys.only." = "question_number", 
    "Matrix.Group.Name" = "matrix_group_name", 
    "Matrix.Ranking." = "matrix_ranking", 
    "Field.Annotation" = "field_annotation")

# Meta Data - Known Field Types 

#' @rdname redcapDataStructures
#' @export

REDCAP_METADATA_FIELDTYPE <- c("calc", 
                               "checkbox", 
                               "descriptive", 
                               "dropdown", 
                               "file", 
                               "notes", 
                               "radio", 
                               "slider", 
                               "text", 
                               "truefalse", 
                               "yesno")

# Meta Data - Known Validation Types 

#' @rdname redcapDataStructures
#' @export
REDCAP_METADATA_VALIDATION_TYPE <- c(
  "alpha_only",
  "autocomplete",
  "date_dmy", 
  "date_mdy", 
  "date_ymd", 
  "datetime_dmy", 
  "datetime_mdy", 
  "datetime_seconds_dmy", 
  "datetime_seconds_mdy", 
  "datetime_seconds_ymd", 
  "datetime_ymd", 
  "email", 
  "integer", 
  "number", 
  "number_1dp", 
  "number_1dp_comma_decimal", 
  "number_2dp", 
  "number_2dp_comma_decimal",
  "phone", 
  "signature",
  "time", 
  "time_hh_mm_ss",
  "time_mm_ss",
  "vmrn",
  "zipcode")

# Project Information -----------------------------------------------
# Project Information Structure 

REDCAP_PROJECT_INFORMATION_STRUCTURE <- .getStructure('PROJ_INFO', '14.4.0')

# This is the list of fields recognized for updates in importProjectInformation

PROJECT_INFO_FIELDS_EDITABLE <- .getStructure('f_PROJ_INFO_EDIT', '14.4.0')

# These cannot be updated via the API
PROJECT_INFO_FIELDS_FIXED <- .getStructure('f_PROJ_INFO_FIXED', '14.4.0')

# Repeating Instruments and Events ----------------------------------

#' @rdname redcapDataStructures
#' @export

REDCAP_REPEAT_INSTRUMENT_STRUCTURE <- .getStructure('REPEAT_INSTRUMENT', '14.4.0')

# Users -------------------------------------------------------------
# Users Structure

redcapUserStructure <- function(v) .getStructure('USER', v)

# These are variables in the Users table coded as 0 = No Access, 1 = Access
REDCAP_USER_TABLE_ACCESS_VARIABLES <- .getStructure('f_USER', '14.4.0')

# User Roles --------------------------------------------------------
# User Role Structure

redcapUserRoleStructure <- function(v) .getStructure('USER_ROLE', v)

# User Role Table Access Variables

REDCAP_USER_ROLE_TABLE_ACCESS_VARIABLES <- .getStructure('f_USER_ROLE', '14.4.0')

# User-Role Assignment Structure 

REDCAP_USER_ROLE_ASSIGNMENT_STRUCTURE <- .getStructure('USER_ROLE_ASSN', '14.4.0')

# find in code and replace with `.getStructure`
#REDCAP_SYSTEM_FIELDS
#PROJECT_INFO_FIELDS_EDITABLE
#PROJECT_INFO_FIELDS_FIXED
#REDCAP_USER_TABLE_ACCESS_VARIABLES
#REDCAP_USER_ROLE_TABLE_ACCESS_VARIABLES
#REDCAP_ARMS_STRUCTURE
#REDCAP_DAG_STRUCTURE
#REDCAP_DAG_ASSIGNMENT_STRUCTURE
#REDCAP_EVENT_STRUCTURE
#REDCAP_FIELDNAME_STRUCTURE
#REDCAP_INSTRUMENT_STRUCTURE
#REDCAP_INSTRUMENT_MAPPING_STRUCTURE
#REDCAP_LOGGING_STRUCTURE
#REDCAP_METADATA_STRUCTURE
#REDCAP_PROJECT_INFORMATION_STRUCTURE
#REDCAP_REPEAT_INSTRUMENT_STRUCTURE
#REDCAP_USER_STRUCTURE
#REDCAP_USER_ROLE_STRUCTURE
#REDCAP_USER_ROLE_ASSIGNMENT_STRUCTURE
